package app;

import static app.registerForm.getAlphaNumericString;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Earl Appiah - eea7 
 */
public class reportForm extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

//Selected button
    boolean boolLow;
    boolean boolMid;
    boolean boolHigh;

    static String priority;

    //border when selecting and selected
    Border border_select = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
    Border border_selected = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.orange);
    Border border_unselect = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);

    static String employeeNumber = "";
    static String reportID = "";

    //Image path
    String image_path;

    /**
     * Creates new form reportForm
     */
    public reportForm() {
        initComponents();
        Connect();
        //panelbuttons
        lowPan.setBorder(border_selected);
        midPan.setBorder(border_unselect);
        highPan.setBorder(border_unselect);

        //panel set-up
        boolLow = true;
        boolMid = false;
        boolHigh = false;
        priority = "White";
        //image_path = null;

        //details from login
        setReport();
    }

    public void changeBorder(JPanel hover, Border rand) {
        hover.setBorder(rand);
    }

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/maintain", "root", "");

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setReport() {
        changeID();
        employeeNumber = login.getEnum();
        employeeNum.setText(employeeNumber);
        levelShowLabel.setText(priority);

        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        txtDate.setDate(date);
    }

    static String getNumericString(int n) {

        // chose a Character random from this String 
        String numericString = "0123456789";

        // create StringBuffer size of AlphaNumericString 
        StringBuilder sb = new StringBuilder(n);

        for (int i = 0; i < n; i++) {

            // generate a random number between 
            // 0 to AlphaNumericString variable length 
            int index
                    = (int) (numericString.length()
                    * Math.random());

            // add Character one by one in end of sb 
            sb.append(numericString
                    .charAt(index));
        }

        return sb.toString();
    }

    public boolean verifyFields() {
        String textArea = descArea.getText();

        if (textArea.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "One or more fields are empty, check again!", "Empty fields", 2);
            return false;
        } else {
            return true;
        }
    }

    public boolean checkID(String str) {
        PreparedStatement st;
        ResultSet rs;
        boolean id_exist = false;

        String query = "SELECT * FROM reports WHERE id=? ";

        try {
            st = con.prepareStatement(query);
            st.setString(1, str);
            rs = st.executeQuery();

            if (rs.next()) {
                id_exist = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(reportForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id_exist;
    }

    public void changeID() {
        reportID = priority.substring(0, 1) + getNumericString(8);
        while (checkID(reportID)) {
            reportID = priority.substring(0, 1) + getNumericString(8);
        }
        reportNum.setText(reportID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        iconPicture = new javax.swing.JPanel();
        screwIcon = new javax.swing.JLabel();
        innerHeader = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        highLabel = new javax.swing.JLabel();
        medLabel = new javax.swing.JLabel();
        commonLabel = new javax.swing.JLabel();
        lowPan = new javax.swing.JPanel();
        midPan = new javax.swing.JPanel();
        highPan = new javax.swing.JPanel();
        levelShowLabel = new javax.swing.JLabel();
        bodyBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        descLabel = new javax.swing.JLabel();
        reportType = new javax.swing.JComboBox<>();
        employeeNum = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        dateLabel = new javax.swing.JLabel();
        browseImage = new javax.swing.JButton();
        imagePath_label = new javax.swing.JLabel();
        submitReportButton = new javax.swing.JButton();
        reportNumberLabel = new javax.swing.JLabel();
        reportNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(204, 102, 0));

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setPreferredSize(new java.awt.Dimension(550, 77));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPicture.setBackground(new java.awt.Color(51, 51, 51));
        iconPicture.setLayout(new java.awt.BorderLayout());

        screwIcon.setBackground(new java.awt.Color(0, 51, 255));
        screwIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screwIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools-and-utensils.png"))); // NOI18N
        iconPicture.add(screwIcon, java.awt.BorderLayout.CENTER);

        header.add(iconPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 90));

        innerHeader.setBackground(new java.awt.Color(51, 51, 51));
        innerHeader.setLayout(new java.awt.BorderLayout());

        title.setBackground(new java.awt.Color(0, 51, 255));
        title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("REPORT FORM");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setPreferredSize(new java.awt.Dimension(155, 100));
        innerHeader.add(title, java.awt.BorderLayout.PAGE_START);

        header.add(innerHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 620, 90));

        page.setBackground(new java.awt.Color(255, 255, 255));

        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        levelLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        levelLabel.setText("Level of Priority:");
        top.add(levelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, -1));

        highLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        highLabel.setText("High");
        top.add(highLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        medLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        medLabel.setText("Mediate");
        top.add(medLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        commonLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        commonLabel.setText("Common");
        top.add(commonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lowPan.setBackground(new java.awt.Color(255, 255, 255));
        lowPan.setBorder(new javax.swing.border.MatteBorder(null));
        lowPan.setPreferredSize(new java.awt.Dimension(100, 70));
        lowPan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lowPanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lowPanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lowPanMouseExited(evt);
            }
        });
        lowPan.setLayout(new java.awt.BorderLayout());
        top.add(lowPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 110, 80));

        midPan.setBackground(new java.awt.Color(255, 255, 51));
        midPan.setBorder(new javax.swing.border.MatteBorder(null));
        midPan.setPreferredSize(new java.awt.Dimension(100, 70));
        midPan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                midPanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                midPanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                midPanMouseExited(evt);
            }
        });
        midPan.setLayout(new java.awt.BorderLayout());
        top.add(midPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 110, 80));

        highPan.setBackground(new java.awt.Color(255, 0, 0));
        highPan.setBorder(new javax.swing.border.MatteBorder(null));
        highPan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        highPan.setPreferredSize(new java.awt.Dimension(100, 70));
        highPan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                highPanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                highPanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                highPanMouseExited(evt);
            }
        });
        highPan.setLayout(new java.awt.BorderLayout());
        top.add(highPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 110, 80));

        levelShowLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        levelShowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelShowLabel.setText("\"Level\"");
        top.add(levelShowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 80, 160, -1));

        bodyBottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descArea.setColumns(20);
        descArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        descArea.setLineWrap(true);
        descArea.setRows(5);
        jScrollPane1.setViewportView(descArea);

        bodyBottom.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 580, 100));

        descLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descLabel.setText("(Necessary) Description: * ");
        bodyBottom.add(descLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        reportType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passenger Train Car", "Freight Train Car", "Tracks", "Secruity ", "Report", "Other Maintenance" }));
        bodyBottom.add(reportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, -1));

        employeeNum.setBackground(new java.awt.Color(153, 153, 153));
        employeeNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeNum.setText("\"Number\"");
        employeeNum.setOpaque(true);
        bodyBottom.add(employeeNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Type:");
        bodyBottom.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Employee Number:");
        bodyBottom.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Attachment:");
        bodyBottom.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtDate.setDateFormatString("dd-MM-yyyy");
        bodyBottom.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 30));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLabel.setText("Date:");
        bodyBottom.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        browseImage.setText("Select Image ");
        browseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImageActionPerformed(evt);
            }
        });
        bodyBottom.add(browseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, -1));

        imagePath_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        imagePath_label.setText("Image path");
        bodyBottom.add(imagePath_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 390, 20));

        submitReportButton.setBackground(new java.awt.Color(0, 255, 0));
        submitReportButton.setText("Submit");
        submitReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReportButtonActionPerformed(evt);
            }
        });
        bodyBottom.add(submitReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 160, 50));

        reportNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportNumberLabel.setText("Report Number:");
        bodyBottom.add(reportNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        reportNum.setBackground(new java.awt.Color(153, 153, 153));
        reportNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportNum.setText("\"Number\"");
        reportNum.setOpaque(true);
        bodyBottom.add(reportNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 160, -1));

        javax.swing.GroupLayout pageLayout = new javax.swing.GroupLayout(page);
        page.setLayout(pageLayout);
        pageLayout.setHorizontalGroup(
            pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodyBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pageLayout.setVerticalGroup(
            pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void browseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImageActionPerformed
        String path = null;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        //file extension
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*Images", "jpeg", ".jpg", ".png", ".gif");
        fileChooser.addChoosableFileFilter(filter);

        int result = fileChooser.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedImage = fileChooser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            imagePath_label.setText(path);
            image_path = path;
        }
    }//GEN-LAST:event_browseImageActionPerformed

    private void lowPanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowPanMouseEntered
        if (!boolLow) {
            changeBorder(lowPan, border_select);
        }
    }//GEN-LAST:event_lowPanMouseEntered

    private void lowPanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowPanMouseExited
        if (!boolLow) {
            changeBorder(lowPan, border_unselect);
        }
    }//GEN-LAST:event_lowPanMouseExited

    private void midPanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midPanMouseEntered
        if (!boolMid) {
            changeBorder(midPan, border_select);
        }
    }//GEN-LAST:event_midPanMouseEntered

    private void midPanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midPanMouseExited
        if (!boolMid) {
            changeBorder(midPan, border_unselect);
        }
    }//GEN-LAST:event_midPanMouseExited

    private void highPanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highPanMouseEntered
        if (!boolHigh) {
            changeBorder(highPan, border_select);
        }
    }//GEN-LAST:event_highPanMouseEntered

    private void highPanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highPanMouseExited
        if (!boolHigh) {
            changeBorder(highPan, border_unselect);
        }
    }//GEN-LAST:event_highPanMouseExited

    private void lowPanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowPanMouseClicked
        if (!boolLow) {
            boolMid = false;
            boolHigh = false;
            boolLow = true;
            priority = "White";
            levelShowLabel.setText(priority);
            changeBorder(lowPan, border_selected);
            changeBorder(midPan, border_unselect);
            changeBorder(highPan, border_unselect);
            changeID();
        }
    }//GEN-LAST:event_lowPanMouseClicked

    private void midPanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midPanMouseClicked
        if (!boolMid) {
            boolMid = true;
            boolHigh = false;
            boolLow = false;
            priority = "Yellow";
            levelShowLabel.setText(priority);
            changeBorder(lowPan, border_unselect);
            changeBorder(midPan, border_selected);
            changeBorder(highPan, border_unselect);
            changeID();
        }
    }//GEN-LAST:event_midPanMouseClicked

    private void highPanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highPanMouseClicked
        if (!boolHigh) {
            boolMid = false;
            boolHigh = true;
            boolLow = false;
            priority = "Red";
            levelShowLabel.setText(priority);
            changeBorder(lowPan, border_unselect);
            changeBorder(midPan, border_unselect);
            changeBorder(highPan, border_selected);
            changeID();
        }
    }//GEN-LAST:event_highPanMouseClicked

    private void submitReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitReportButtonActionPerformed
        String newID = reportID;
        String colour = priority;
        String description = descArea.getText();
        String rtype = reportType.getSelectedItem().toString();
        String enumber = employeeNumber;
        SimpleDateFormat date_form = new SimpleDateFormat("dd-MM-yyyy");
        String date = date_form.format(txtDate.getDate());
        if (verifyFields()) {
            PreparedStatement pst;
            String query = "INSERT INTO `reports`(`id`, `colour`, `descrip`,`type`, `enum`, `date`, `picture`) VALUES (?,?,?,?,?,?,?)";

            int p = JOptionPane.showConfirmDialog(null, "Do you want to confirm report done?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                try {
                    pst = con.prepareStatement(query);
                    pst.setString(1, newID);
                    pst.setString(2, colour);
                    pst.setString(3, description);
                    pst.setString(4, rtype);
                    pst.setString(5, enumber);
                    pst.setString(6, date);
                    //save image as blob
                    try {
                        if (image_path != null) {
                            InputStream image = new FileInputStream(new File(image_path));
                            pst.setBlob(7, image);
                        } else {
                            pst.setNull(7, java.sql.Types.NULL);
                        }

                        if (pst.executeUpdate() != 0) {
                            JOptionPane.showMessageDialog(null, "Record sucessfully saved!");
                            changeID();
                            reportForm a = new reportForm();
                            a.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Record had an error recording");
                        }

                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(reportForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_submitReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel bodyBottom;
    private javax.swing.JButton browseImage;
    private javax.swing.JLabel commonLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextArea descArea;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel employeeNum;
    private javax.swing.JPanel header;
    private javax.swing.JLabel highLabel;
    private javax.swing.JPanel highPan;
    private javax.swing.JPanel iconPicture;
    private javax.swing.JLabel imagePath_label;
    private javax.swing.JPanel innerHeader;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel levelShowLabel;
    private javax.swing.JPanel lowPan;
    private javax.swing.JLabel medLabel;
    private javax.swing.JPanel midPan;
    private javax.swing.JPanel page;
    private javax.swing.JLabel reportNum;
    private javax.swing.JLabel reportNumberLabel;
    private javax.swing.JComboBox<String> reportType;
    private javax.swing.JLabel screwIcon;
    private javax.swing.JButton submitReportButton;
    private javax.swing.JLabel title;
    private javax.swing.JPanel top;
    private com.toedter.calendar.JDateChooser txtDate;
    // End of variables declaration//GEN-END:variables
}
